# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19GtMkn-krgPsP1wxEEqNqxRwbD7FdLRZ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


df = pd.read_excel("credits_100.xlsx")
print(df.head(10))
sns.pairplot(df, height=3, aspect=1.5, vars=['salary', 'credit', 'married'], diag_kind='kde', kind='reg')
print()
print('корреляция между числовыми признаками')
fields = ['age', 'salary', 'married', 'children', 'credit']
corr = df[fields].corr()
print(corr)

mask = np.zeros_like(corr, dtype=np.bool)
mask[np.triu_indices_from(mask)] = True
sns.heatmap(corr,mask=mask, cmap=sns.light_palette('grey'))

from mpl_toolkits.mplot3d import axes3d
fig = plt.figure(figsize=(10, 10))
ax = fig.add_subplot(111, projection='3d')
x1 = df['salary']
y1 = df['married']
z1 = df['credit']
ax.scatter(x1, y1, z1, marker='o', label='blue')

plt.figure(figsize=(16, 6))
df.boxplot(column=['salary', 'credit'], vert=False)

plt.show()
print('построение регрессионно модели')
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics

X = df[['credit','age', 'married', 'children']]
y = df['salary']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=80)
print(X_test[:5])
print(y_test[:5])

#тренируем регрессию
regressor = LinearRegression()
regressor.fit(X_train, y_train)
print('коэф-ты регрессии')
print(regressor.coef_)

#расчетные значения у для X_test
y_pred = regressor.predict(X_test)
for y1, y2 in zip(y_test[:10], y_pred[:10]):
  print(y1, y2)

E = [abs(y1 - y2) / ((y1+y2)/2) for y1, y2 in zip(y_test, y_pred)]
print(E)

avg_E = sum(E) / len(E)
print('оценка точности')
print(f'E среднее = {avg_E:.3f}')

accuracy = regressor.score(X_test, y_test)
print(accuracy)